services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: ${CONTAINER_NAME_DB}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PGDATA_PATH}:/pgdata
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${CONTAINER_NAME_RABBITMQ}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_DATA_PATH}:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
